// Bindings for `chromaprint.h`.
//
// Low-level FFI bindings for the Chromaprint C library, generated by
// `package:ffigen`. These bindings provide direct access to the native
// chromaprint functions. Most users should use the high-level [Chromaprint]
// class from `package:chromaprint/chromaprint.dart` instead.
//
// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
//
// ignore_for_file: always_specify_types, type_literal_in_constant_list
// ignore_for_file: non_constant_identifier_names, camel_case_types
// ignore_for_file: unused_import, unnecessary_import, annotate_overrides

import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';

/// Opaque chromaprint context.
///
/// Represents an opaque native chromaprint fingerprinting context.
/// Instances are created by [ChromaprintBindings.chromaprint_new] and
/// must be freed with [ChromaprintBindings.chromaprint_free].
final class ChromaprintContext extends ffi.Opaque {}

/// Opaque chromaprint matcher context.
final class ChromaprintMatcherContext extends ffi.Opaque {}

/// Bindings for the chromaprint C library.
class ChromaprintBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  ChromaprintBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  ChromaprintBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Returns the version string of the chromaprint library.
  ffi.Pointer<ffi.Char> chromaprint_get_version() {
    return _chromaprint_get_version();
  }

  late final _chromaprint_get_versionPtr = _lookup<
      ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
    'chromaprint_get_version',
  );
  late final _chromaprint_get_version = _chromaprint_get_versionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// Creates a new chromaprint context.
  ///
  /// [algorithm] specifies the fingerprint algorithm to use
  /// (one of the CHROMAPRINT_ALGORITHM_* values).
  /// Returns a pointer to the new context, or NULL on error.
  ffi.Pointer<ChromaprintContext> chromaprint_new(int algorithm) {
    return _chromaprint_new(algorithm);
  }

  late final _chromaprint_newPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ChromaprintContext> Function(ffi.Int)>>(
    'chromaprint_new',
  );
  late final _chromaprint_new = _chromaprint_newPtr
      .asFunction<ffi.Pointer<ChromaprintContext> Function(int)>();

  /// Frees a chromaprint context.
  void chromaprint_free(ffi.Pointer<ChromaprintContext> ctx) {
    return _chromaprint_free(ctx);
  }

  late final _chromaprint_freePtr = _lookup<
      ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ChromaprintContext>)>>(
    'chromaprint_free',
  );
  late final _chromaprint_free = _chromaprint_freePtr
      .asFunction<void Function(ffi.Pointer<ChromaprintContext>)>();

  /// Returns the algorithm used by the context.
  int chromaprint_get_algorithm(ffi.Pointer<ChromaprintContext> ctx) {
    return _chromaprint_get_algorithm(ctx);
  }

  late final _chromaprint_get_algorithmPtr = _lookup<
      ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ChromaprintContext>)>>(
    'chromaprint_get_algorithm',
  );
  late final _chromaprint_get_algorithm = _chromaprint_get_algorithmPtr
      .asFunction<int Function(ffi.Pointer<ChromaprintContext>)>();

  /// Sets an option on the context.
  ///
  /// Returns 1 on success, 0 on error.
  int chromaprint_set_option(
    ffi.Pointer<ChromaprintContext> ctx,
    ffi.Pointer<ffi.Char> name,
    int value,
  ) {
    return _chromaprint_set_option(ctx, name, value);
  }

  late final _chromaprint_set_optionPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ChromaprintContext>,
            ffi.Pointer<ffi.Char>,
            ffi.Int,
          )>>('chromaprint_set_option');
  late final _chromaprint_set_option = _chromaprint_set_optionPtr.asFunction<
      int Function(ffi.Pointer<ChromaprintContext>, ffi.Pointer<ffi.Char>, int)>();

  /// Returns the number of channels configured on the context.
  int chromaprint_get_num_channels(ffi.Pointer<ChromaprintContext> ctx) {
    return _chromaprint_get_num_channels(ctx);
  }

  late final _chromaprint_get_num_channelsPtr = _lookup<
      ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ChromaprintContext>)>>(
    'chromaprint_get_num_channels',
  );
  late final _chromaprint_get_num_channels = _chromaprint_get_num_channelsPtr
      .asFunction<int Function(ffi.Pointer<ChromaprintContext>)>();

  /// Returns the sample rate configured on the context.
  int chromaprint_get_sample_rate(ffi.Pointer<ChromaprintContext> ctx) {
    return _chromaprint_get_sample_rate(ctx);
  }

  late final _chromaprint_get_sample_ratePtr = _lookup<
      ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ChromaprintContext>)>>(
    'chromaprint_get_sample_rate',
  );
  late final _chromaprint_get_sample_rate = _chromaprint_get_sample_ratePtr
      .asFunction<int Function(ffi.Pointer<ChromaprintContext>)>();

  /// Returns the item duration in samples.
  int chromaprint_get_item_duration(ffi.Pointer<ChromaprintContext> ctx) {
    return _chromaprint_get_item_duration(ctx);
  }

  late final _chromaprint_get_item_durationPtr = _lookup<
      ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ChromaprintContext>)>>(
    'chromaprint_get_item_duration',
  );
  late final _chromaprint_get_item_duration = _chromaprint_get_item_durationPtr
      .asFunction<int Function(ffi.Pointer<ChromaprintContext>)>();

  /// Returns the item duration in milliseconds.
  int chromaprint_get_item_duration_ms(ffi.Pointer<ChromaprintContext> ctx) {
    return _chromaprint_get_item_duration_ms(ctx);
  }

  late final _chromaprint_get_item_duration_msPtr = _lookup<
      ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ChromaprintContext>)>>(
    'chromaprint_get_item_duration_ms',
  );
  late final _chromaprint_get_item_duration_ms =
      _chromaprint_get_item_duration_msPtr
          .asFunction<int Function(ffi.Pointer<ChromaprintContext>)>();

  /// Returns the delay in samples.
  int chromaprint_get_delay(ffi.Pointer<ChromaprintContext> ctx) {
    return _chromaprint_get_delay(ctx);
  }

  late final _chromaprint_get_delayPtr = _lookup<
      ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ChromaprintContext>)>>(
    'chromaprint_get_delay',
  );
  late final _chromaprint_get_delay = _chromaprint_get_delayPtr
      .asFunction<int Function(ffi.Pointer<ChromaprintContext>)>();

  /// Returns the delay in milliseconds.
  int chromaprint_get_delay_ms(ffi.Pointer<ChromaprintContext> ctx) {
    return _chromaprint_get_delay_ms(ctx);
  }

  late final _chromaprint_get_delay_msPtr = _lookup<
      ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ChromaprintContext>)>>(
    'chromaprint_get_delay_ms',
  );
  late final _chromaprint_get_delay_ms = _chromaprint_get_delay_msPtr
      .asFunction<int Function(ffi.Pointer<ChromaprintContext>)>();

  /// Starts audio fingerprinting.
  ///
  /// [sample_rate] is the sample rate in Hz.
  /// [num_channels] is the number of audio channels (1 or 2).
  /// Returns 1 on success, 0 on error.
  int chromaprint_start(
    ffi.Pointer<ChromaprintContext> ctx,
    int sample_rate,
    int num_channels,
  ) {
    return _chromaprint_start(ctx, sample_rate, num_channels);
  }

  late final _chromaprint_startPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ChromaprintContext>,
            ffi.Int,
            ffi.Int,
          )>>('chromaprint_start');
  late final _chromaprint_start = _chromaprint_startPtr
      .asFunction<int Function(ffi.Pointer<ChromaprintContext>, int, int)>();

  /// Feeds audio data to the fingerprinter.
  ///
  /// [data] is a pointer to 16-bit signed integer samples in native byte order.
  /// [size] is the number of samples (not bytes).
  /// Returns 1 on success, 0 on error.
  int chromaprint_feed(
    ffi.Pointer<ChromaprintContext> ctx,
    ffi.Pointer<ffi.Int16> data,
    int size,
  ) {
    return _chromaprint_feed(ctx, data, size);
  }

  late final _chromaprint_feedPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ChromaprintContext>,
            ffi.Pointer<ffi.Int16>,
            ffi.Int,
          )>>('chromaprint_feed');
  late final _chromaprint_feed = _chromaprint_feedPtr.asFunction<
      int Function(ffi.Pointer<ChromaprintContext>, ffi.Pointer<ffi.Int16>, int)>();

  /// Finishes audio fingerprinting.
  ///
  /// Returns 1 on success, 0 on error.
  int chromaprint_finish(ffi.Pointer<ChromaprintContext> ctx) {
    return _chromaprint_finish(ctx);
  }

  late final _chromaprint_finishPtr = _lookup<
      ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ChromaprintContext>)>>(
    'chromaprint_finish',
  );
  late final _chromaprint_finish = _chromaprint_finishPtr
      .asFunction<int Function(ffi.Pointer<ChromaprintContext>)>();

  /// Clears the current fingerprint data.
  ///
  /// Returns 1 on success, 0 on error.
  int chromaprint_clear_fingerprint(ffi.Pointer<ChromaprintContext> ctx) {
    return _chromaprint_clear_fingerprint(ctx);
  }

  late final _chromaprint_clear_fingerprintPtr = _lookup<
      ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ChromaprintContext>)>>(
    'chromaprint_clear_fingerprint',
  );
  late final _chromaprint_clear_fingerprint =
      _chromaprint_clear_fingerprintPtr
          .asFunction<int Function(ffi.Pointer<ChromaprintContext>)>();

  /// Gets the compressed fingerprint as a base64-encoded string.
  ///
  /// [fingerprint] is set to point to a newly allocated string.
  /// The caller must free it with [chromaprint_dealloc].
  /// Returns 1 on success, 0 on error.
  int chromaprint_get_fingerprint(
    ffi.Pointer<ChromaprintContext> ctx,
    ffi.Pointer<ffi.Pointer<ffi.Char>> fingerprint,
  ) {
    return _chromaprint_get_fingerprint(ctx, fingerprint);
  }

  late final _chromaprint_get_fingerprintPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ChromaprintContext>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )>>('chromaprint_get_fingerprint');
  late final _chromaprint_get_fingerprint =
      _chromaprint_get_fingerprintPtr.asFunction<
          int Function(
            ffi.Pointer<ChromaprintContext>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )>();

  /// Gets the raw fingerprint as an array of 32-bit unsigned integers.
  ///
  /// [fingerprint] is set to point to a newly allocated array.
  /// [size] is set to the number of elements.
  /// The caller must free the array with [chromaprint_dealloc].
  /// Returns 1 on success, 0 on error.
  int chromaprint_get_raw_fingerprint(
    ffi.Pointer<ChromaprintContext> ctx,
    ffi.Pointer<ffi.Pointer<ffi.Uint32>> fingerprint,
    ffi.Pointer<ffi.Int> size,
  ) {
    return _chromaprint_get_raw_fingerprint(ctx, fingerprint, size);
  }

  late final _chromaprint_get_raw_fingerprintPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ChromaprintContext>,
            ffi.Pointer<ffi.Pointer<ffi.Uint32>>,
            ffi.Pointer<ffi.Int>,
          )>>('chromaprint_get_raw_fingerprint');
  late final _chromaprint_get_raw_fingerprint =
      _chromaprint_get_raw_fingerprintPtr.asFunction<
          int Function(
            ffi.Pointer<ChromaprintContext>,
            ffi.Pointer<ffi.Pointer<ffi.Uint32>>,
            ffi.Pointer<ffi.Int>,
          )>();

  /// Gets the size of the raw fingerprint.
  ///
  /// [size] is set to the number of elements.
  /// Returns 1 on success, 0 on error.
  int chromaprint_get_raw_fingerprint_size(
    ffi.Pointer<ChromaprintContext> ctx,
    ffi.Pointer<ffi.Int> size,
  ) {
    return _chromaprint_get_raw_fingerprint_size(ctx, size);
  }

  late final _chromaprint_get_raw_fingerprint_sizePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ChromaprintContext>,
            ffi.Pointer<ffi.Int>,
          )>>('chromaprint_get_raw_fingerprint_size');
  late final _chromaprint_get_raw_fingerprint_size =
      _chromaprint_get_raw_fingerprint_sizePtr.asFunction<
          int Function(ffi.Pointer<ChromaprintContext>, ffi.Pointer<ffi.Int>)>();

  /// Gets a hash of the fingerprint.
  ///
  /// [hash] is set to the 32-bit hash value.
  /// Returns 1 on success, 0 on error.
  int chromaprint_get_fingerprint_hash(
    ffi.Pointer<ChromaprintContext> ctx,
    ffi.Pointer<ffi.Uint32> hash,
  ) {
    return _chromaprint_get_fingerprint_hash(ctx, hash);
  }

  late final _chromaprint_get_fingerprint_hashPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ChromaprintContext>,
            ffi.Pointer<ffi.Uint32>,
          )>>('chromaprint_get_fingerprint_hash');
  late final _chromaprint_get_fingerprint_hash =
      _chromaprint_get_fingerprint_hashPtr.asFunction<
          int Function(ffi.Pointer<ChromaprintContext>, ffi.Pointer<ffi.Uint32>)>();

  /// Encodes a raw fingerprint to a compressed format.
  ///
  /// [fp] is the raw fingerprint array.
  /// [size] is the number of elements in [fp].
  /// [algorithm] is the algorithm used to generate the fingerprint.
  /// [encoded_fp] is set to the encoded data (must be freed with [chromaprint_dealloc]).
  /// [encoded_size] is set to the size of the encoded data.
  /// [base64] if non-zero, the result is base64-encoded.
  /// Returns 1 on success, 0 on error.
  int chromaprint_encode_fingerprint(
    ffi.Pointer<ffi.Uint32> fp,
    int size,
    int algorithm,
    ffi.Pointer<ffi.Pointer<ffi.Char>> encoded_fp,
    ffi.Pointer<ffi.Int> encoded_size,
    int base64,
  ) {
    return _chromaprint_encode_fingerprint(
        fp, size, algorithm, encoded_fp, encoded_size, base64);
  }

  late final _chromaprint_encode_fingerprintPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Uint32>,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Int>,
            ffi.Int,
          )>>('chromaprint_encode_fingerprint');
  late final _chromaprint_encode_fingerprint =
      _chromaprint_encode_fingerprintPtr.asFunction<
          int Function(
            ffi.Pointer<ffi.Uint32>,
            int,
            int,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Int>,
            int,
          )>();

  /// Decodes a compressed fingerprint.
  ///
  /// [encoded_fp] is the encoded fingerprint data.
  /// [encoded_size] is the size of the encoded data, or -1 if it's a null-terminated string.
  /// [fp] is set to the decoded raw fingerprint (must be freed with [chromaprint_dealloc]).
  /// [size] is set to the number of elements in [fp].
  /// [algorithm] is set to the algorithm used to generate the fingerprint.
  /// [base64] if non-zero, the input is base64-encoded.
  /// Returns 1 on success, 0 on error.
  int chromaprint_decode_fingerprint(
    ffi.Pointer<ffi.Char> encoded_fp,
    int encoded_size,
    ffi.Pointer<ffi.Pointer<ffi.Uint32>> fp,
    ffi.Pointer<ffi.Int> size,
    ffi.Pointer<ffi.Int> algorithm,
    int base64,
  ) {
    return _chromaprint_decode_fingerprint(
        encoded_fp, encoded_size, fp, size, algorithm, base64);
  }

  late final _chromaprint_decode_fingerprintPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Pointer<ffi.Pointer<ffi.Uint32>>,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
            ffi.Int,
          )>>('chromaprint_decode_fingerprint');
  late final _chromaprint_decode_fingerprint =
      _chromaprint_decode_fingerprintPtr.asFunction<
          int Function(
            ffi.Pointer<ffi.Char>,
            int,
            ffi.Pointer<ffi.Pointer<ffi.Uint32>>,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
            int,
          )>();

  /// Decodes only the header of a compressed fingerprint.
  ///
  /// [encoded_fp] is the encoded fingerprint data.
  /// [encoded_size] is the size of the encoded data, or -1 if null-terminated.
  /// [size] is set to the number of raw fingerprint elements.
  /// [algorithm] is set to the algorithm used.
  /// [base64] if non-zero, the input is base64-encoded.
  /// Returns 1 on success, 0 on error.
  int chromaprint_decode_fingerprint_header(
    ffi.Pointer<ffi.Char> encoded_fp,
    int encoded_size,
    ffi.Pointer<ffi.Int> size,
    ffi.Pointer<ffi.Int> algorithm,
    int base64,
  ) {
    return _chromaprint_decode_fingerprint_header(
        encoded_fp, encoded_size, size, algorithm, base64);
  }

  late final _chromaprint_decode_fingerprint_headerPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
            ffi.Int,
          )>>('chromaprint_decode_fingerprint_header');
  late final _chromaprint_decode_fingerprint_header =
      _chromaprint_decode_fingerprint_headerPtr.asFunction<
          int Function(
            ffi.Pointer<ffi.Char>,
            int,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
            int,
          )>();

  /// Computes a hash of a raw fingerprint.
  ///
  /// [fp] is the raw fingerprint array.
  /// [size] is the number of elements.
  /// [hash] is set to the 32-bit hash value.
  /// Returns 1 on success, 0 on error.
  int chromaprint_hash_fingerprint(
    ffi.Pointer<ffi.Uint32> fp,
    int size,
    ffi.Pointer<ffi.Uint32> hash,
  ) {
    return _chromaprint_hash_fingerprint(fp, size, hash);
  }

  late final _chromaprint_hash_fingerprintPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Uint32>,
            ffi.Int,
            ffi.Pointer<ffi.Uint32>,
          )>>('chromaprint_hash_fingerprint');
  late final _chromaprint_hash_fingerprint =
      _chromaprint_hash_fingerprintPtr.asFunction<
          int Function(ffi.Pointer<ffi.Uint32>, int, ffi.Pointer<ffi.Uint32>)>();

  /// Frees memory allocated by chromaprint functions.
  void chromaprint_dealloc(ffi.Pointer<ffi.Void> ptr) {
    return _chromaprint_dealloc(ptr);
  }

  late final _chromaprint_deallocPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
    'chromaprint_dealloc',
  );
  late final _chromaprint_dealloc = _chromaprint_deallocPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
