#ifndef CHROMAPRINT_CONFIG_H
#define CHROMAPRINT_CONFIG_H

#define HAVE_LRINTF 1
#define HAVE_ROUND 1

#define USE_KISSFFT 1
#define USE_INTERNAL_AVRESAMPLE 1

#define CHROMAPRINT_VERSION_MAJOR 1
#define CHROMAPRINT_VERSION_MINOR 6
#define CHROMAPRINT_VERSION_PATCH 0

#endif
